version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    volumes:
     - ./frontend:/frontend
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - "3000:3000"
    
